# Generated by Django 3.2.8 on 2021-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=40)),
                ('ticketGroup', models.CharField(max_length=20)),
                ('ticketKeyword', models.CharField(max_length=20)),
            ],
        ),
    ]
