# Generated by Django 3.2.8 on 2021-10-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('vid', models.CharField(max_length=10)),
                ('lecturer', models.CharField(max_length=60)),
                ('theme', models.CharField(max_length=40)),
                ('thumb_url', models.CharField(default='', max_length=128)),
                ('duration', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTime', models.IntegerField(default=0)),
                ('is_like', models.BooleanField(default=False)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth0login.media')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=40)),
                ('ticketGroup', models.CharField(max_length=20)),
                ('ticketKeyword', models.CharField(max_length=20)),
                ('ticketCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affi', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('viewcount', models.ManyToManyField(to='auth0login.MediaViewCount')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('mlist', models.ManyToManyField(to='auth0login.Media')),
            ],
        ),
    ]
