# Generated by Django 2.2.28 on 2023-08-03 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('vid', models.CharField(max_length=10)),
                ('lecturer', models.CharField(max_length=60)),
                ('theme', models.CharField(max_length=40)),
                ('thumb_url', models.CharField(blank=True, default='', max_length=128)),
                ('duration', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTime', models.IntegerField(default=0)),
                ('is_like', models.BooleanField(default=False)),
                ('totalViewSec', models.IntegerField(default=0)),
                ('view_speed', models.FloatField(default=1.0)),
                ('viewstart_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastview_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth0login.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=40)),
                ('ticketGroup', models.CharField(max_length=20)),
                ('ticketKeyword', models.CharField(max_length=20)),
                ('ticketType', models.CharField(default='', max_length=20)),
                ('ticketUntil', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticketCount', models.IntegerField(default=0)),
                ('ticketCourse', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='auth0login.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affi', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastlogin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tickets', models.ManyToManyField(to='auth0login.Ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('viewcount', models.ManyToManyField(to='auth0login.MediaViewCount')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='mlist',
            field=models.ManyToManyField(to='auth0login.Media'),
        ),
    ]
