# Generated by Django 3.2.8 on 2021-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumb_url',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
