# Generated by Django 3.2.8 on 2021-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0003_auto_20211011_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
