# Generated by Django 3.2.8 on 2021-10-15 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth0login', '0006_auto_20211011_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affi', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to=settings.AUTH_USER_MODEL)),
                ('viewcount', models.ManyToManyField(to='auth0login.MediaViewCount')),
            ],
        ),
        migrations.DeleteModel(
            name='TOUser',
        ),
    ]
