# Generated by Django 3.2.8 on 2021-10-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
