# Generated by Django 3.2.8 on 2021-10-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0009_auto_20211016_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumb_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
